export const siteConfig = {
  name: "Salma Mahjoub",
  title: "Salma Mahjoub | Creative Mobile & Full-Stack Developer",
  description:
    "Portfolio of Salma Mahjoub, a creative mobile and full-stack developer building polished apps, web platforms and AI-powered products. Open to a PFE internship from January 2027.",
  url: "https://salma.me",
  email: "mahjoub2003@gmail.com",
  phone: "+216 25 305 902",
  phoneHref: "tel:+21625305902",
  github: "https://github.com/salma-mahjoub",
  linkedin: "https://www.linkedin.com/in/salma-mahjoub-706b87246/",
  pinterest: "https://www.pinterest.com/Salma_mahjoub_/",
  keywords: [
    "Salma Mahjoub",
    "software engineer",
    "mobile developer",
    "full-stack developer",
    "Next.js",
    "Flutter",
    "SwiftUI",
    "Kotlin Jetpack Compose",
    "NestJS",
    "Machine Learning",
    "NLP",
    "Computer Vision",
    "ABAP",
    "Tunis",
  ],
} as const;
