export const siteConfig = {
  name: "Salma Mahjoub",
  title: "Salma Mahjoub | Mobile Information Systems Engineer",
  description:
    "Software engineering portfolio for Salma Mahjoub, a Tunis-based computer science engineering student building mobile, AI, and digital product experiences.",
  url: "https://salma.me",
  email: "mahjoub2003@gmail.com",
  phone: "+216 25 305 902",
  phoneHref: "tel:+21625305902",
  github: "https://github.com/salma-mahjoub",
  linkedin: "https://linkedin.com/in/salma-mahjoub",
  pinterest: "https://www.pinterest.com/Salma_mahjoub_/",
  keywords: [
    "Salma Mahjoub",
    "software engineer",
    "mobile developer",
    "full-stack developer",
    "Next.js",
    "Flutter",
    "SwiftUI",
    "Kotlin Jetpack Compose",
    "NestJS",
    "Machine Learning",
    "NLP",
    "Computer Vision",
    "ABAP",
    "Tunis",
  ],
} as const;
